// Code generated by build.rs DO NOT EDIT.
// VERSION: 1.5.0.0
// Maintainers: ["zhanglei.sec@bytedance.com"]
pub const KO_URL: &[&str] = &["http://example.com/download/ko/"];
pub const NAME: &str = "hids_driver";
pub const PIPE_PATH: &str = "/proc/hids_driver/1";
pub const SOCKET_PATH: &str = "../plugin.sock";
pub const VERSION: &str = "1.5.0.0";
