#!/bin/bash
#This script is dynamic mount container volumens
set -e
PID=$1
HOSTPATH=$2
CONTPATH=$3
NSENTER_PATH=$4

if [ ! -d $HOSTPATH ];then
    echo "physics $HOSTPATH is not exist!"
    exit 1
fi

REALPATH=$(readlink --canonicalize $HOSTPATH)

FILESYS=$(df -P $REALPATH | tail -n 1 | awk '{print $6}')

while read DEV MOUNT JUNK
    do
        [ $MOUNT = $FILESYS ] && [ $DEV != "rootfs" ] && break
    done </proc/mounts
[ $MOUNT = $FILESYS ] # Sanity check!

while read A B C SUBROOT MOUNT JUNK
    do [ $MOUNT = $FILESYS ] && break
    done < /proc/self/mountinfo

[ $MOUNT = $FILESYS ] # Moar sanity check!
SUBPATH=$(echo $REALPATH | sed s,^$FILESYS,,)
DEVDEC=$(printf "%d %d" $(stat --format "0x%t 0x%T" $DEV))
run_command="$NSENTER_PATH --target $PID --mount --uts --ipc --net --pid -- sh -c"
if  [ `$run_command "mount|grep $CONTPATH|wc -l"` -ne 0 ];then
    echo "container  mount dir $CONTPATH is mounting!"
    exit 0
fi
$run_command "[ -b $DEV ] ||mknod --mode 0600 $DEV b $DEVDEC"
$run_command "mkdir /tmpmnt"
$run_command "mount $DEV /tmpmnt"
$run_command "mkdir -p $CONTPATH"
$run_command "mount -o bind /tmpmnt/$SUBROOT/$SUBPATH $CONTPATH"
$run_command "umount /tmpmnt"
$run_command "rmdir /tmpmnt"
check_result=`$run_command "mount|grep $CONTPATH|wc -l"`
if [ $check_result -ne 0 ];then
    echo "dynamic mount physics $HOSTPATH on $PID $CONTPATH is success!"
else
    echo "dynamic mount physics $HOSTPATH on $PID $CONTPATH is fail!"
fi
