FROM ubuntu:xenial AS xenial

RUN apt update;
RUN apt install -y wget curl tree git gcc build-essential kbuild libelf-dev;
RUN apt-get -y install linux-headers-4.8.*-generic  || true
RUN apt clean all

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/x86_64/batch_compile.sh

RUN apt-get -y remove linux-headers-4.8.*-generic  || true

FROM ubuntu:xenial
COPY --from=0 /ko_output /ko_output
CMD [ "sh", "-c", "echo start" ]