FROM cern/cc7-base:latest AS rhel7

RUN yum install -y wget perl gcc make tree elfutils-libelf-devel yumdownloader pciutils-libs; 
RUN yum groupinstall -y  "Development Tools"; 
RUN mkdir -p /ko_output

ADD . /elkeid
WORKDIR /elkeid/driver

RUN bash ./build_script/x86_64/batch_compile_elrepo7_ml.sh
