FROM ubuntu:focal AS focal_aws

RUN apt update;
RUN apt install -y wget curl tree git gcc build-essential kbuild libelf-dev;
RUN apt-get -y install linux-headers-*-aws || true
RUN apt clean all

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/x86_64/batch_compile.sh

RUN apt-get -y remove linux-headers-*-aws || true

FROM ubuntu:focal
COPY --from=0 /ko_output /ko_output
CMD [ "sh", "-c", "echo start" ]