FROM rockylinux:9 AS rockylinux9

RUN dnf install -y wget perl gcc make tree elfutils-libelf-devel openssl-devel; 

RUN yum groupinstall -y  "Development Tools"; 
RUN rm -rf /root/headers || true
RUN mkdir /root/headers

WORKDIR /root/headers
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky/9/BaseOS/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky/9/AppStream/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky/9/devel/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky/9.2/BaseOS/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky/9.2/AppStream/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky/9.2/devel/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky/9.3/BaseOS/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky/9.3/AppStream/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky/9.3/devel/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky-vault/9.0/devel/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky-vault/9.0/AppStream/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky-vault/9.1/devel/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky-vault/9.1/AppStream/x86_64/os/Packages/k/' || true ;
RUN wget -q -k -e robots=off -c -r -np -nd -nH -A  'kernel-devel*x86_64.rpm' 'https://mirrors.nju.edu.cn/rocky-vault/9.1/BaseOS/x86_64/os/Packages/k/' || true ;

RUN rm -f /root/headers/kernel-devel-matched*
RUN rpm --force -i /root/headers/*.rpm || true

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/x86_64/batch_compile.sh
RUN rm -rf /root/headers/*.rpm 


