FROM ubuntu:xenial AS xenial_gcp

RUN apt update;
RUN apt install -y wget curl tree git gcc build-essential kbuild libelf-dev;
RUN apt-get -y install linux-headers-generic-hwe-16.04* || true
RUN apt clean all

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/x86_64/batch_compile.sh

RUN apt-get -y remove linux-headers-generic-hwe-16.04* || true
