FROM cern/c8-base:latest AS rhel8

RUN yum install -y wget perl gcc make tree elfutils-libelf-devel; 
RUN yum groupinstall -y  "Development Tools"; 
RUN mkdir /root/headers

RUN cd /root/headers; \
wget -q -c -r -np -nd -nH -A 'kernel-devel*x86_64.rpm' 'https://mirrors.tuna.tsinghua.edu.cn/cc/8.0/BaseOS/x86_64/os/Packages/'; \
wget -q -c -r -np -nd -nH -A 'kernel-devel*x86_64.rpm' 'https://mirrors.tuna.tsinghua.edu.cn/cc/8.1/BaseOS/x86_64/os/Packages/'; \
wget -q -c -r -np -nd -nH -A 'kernel-devel*x86_64.rpm' 'https://mirrors.tuna.tsinghua.edu.cn/cc/8.2/BaseOS/x86_64/os/Packages/'; \
wget -q -c -r -np -nd -nH -A 'kernel-devel*x86_64.rpm' 'https://mirrors.tuna.tsinghua.edu.cn/cc/8.3/BaseOS/x86_64/os/Packages/';  \
wget -q -c -r -np -nd -nH -A 'kernel-devel*x86_64.rpm' 'https://mirrors.tuna.tsinghua.edu.cn/cc/8.4/BaseOS/x86_64/os/Packages/';  \
wget -q -c -r -np -nd -nH -A 'kernel-devel*x86_64.rpm' 'https://mirrors.tuna.tsinghua.edu.cn/cc/8.5/BaseOS/x86_64/os/Packages/'; \
wget -q -c -r -np -nd -nH -A 'kernel-devel*x86_64.rpm' 'http://repos-va.psychz.net/centos/8-stream/BaseOS/x86_64/os/Packages/';

RUN rpm --force -i /root/headers/*.rpm || true

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/x86_64/batch_compile.sh
RUN rm -rf /root/headers/*.rpm 


