FROM tencentos/tencentos_server24:latest AS tlinux24
CMD [ "sh", "-c", "echo start" ]

RUN yum install -y wget perl gcc make tree elfutils-libelf-devel yumdownloader; 
RUN yum groupinstall -y  "Development Tools"; 

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/x86_64/batch_compile_tencentos.sh

FROM tencentos/tencentos_server24:latest
COPY --from=0 /ko_output /ko_output
CMD [ "sh", "-c", "echo start" ]