FROM ubuntu:jammy AS jammy

RUN apt update;
RUN apt install -y wget curl tree git gcc build-essential kbuild libelf-dev;
RUN apt-get -y install linux-headers || true
RUN apt-get -y install linux-headers-*-azure || true

RUN apt clean all

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/x86_64/batch_compile.sh

RUN apt-get -y remove linux-headers-*-azure || true

FROM ubuntu:jammy
COPY --from=0 /ko_output /ko_output
CMD [ "sh", "-c", "echo start" ]