FROM ubuntu:xenial AS xenial

RUN apt update;
RUN apt install -y wget curl tree git gcc build-essential kbuild libelf-dev;
RUN apt-get -y install linux-headers-4.4.*-generic  || true
RUN apt clean all

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/x86_64/batch_compile.sh

RUN apt-get -y remove linux-headers-4.4.*-generic  || true