FROM cern/c8-base:latest AS rhel8

RUN yum install -y wget perl gcc make tree elfutils-libelf-devel pciutils-libs; 
RUN yum groupinstall -y  "Development Tools"; 

RUN mkdir -p /ko_output


ADD . /elkeid
WORKDIR /elkeid/driver

RUN bash ./build_script/x86_64/batch_compile_elrepo8_ml.sh
RUN yum remove -y kernel-devel || true


FROM cern/c8-base:latest
COPY --from=0 /ko_output /ko_output
CMD [ "sh", "-c", "echo start" ]