FROM cern/cc7-base:latest AS rhel7

RUN yum install -y wget perl gcc make tree elfutils-libelf-devel yumdownloader; 
RUN yum groupinstall -y  "Development Tools"; 
RUN mkdir /root/headers
RUN cd /root/headers; wget -q -c -r -np -nd -nH -A 'kernel*devel*x86_64.rpm' 'http://mirrors.coreix.net/elrepo-archive-archive/kernel/el7/x86_64/RPMS/'
RUN rpm --force -ivh /root/headers/*.rpm || true

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./batch_compile.sh
RUN rm -rf /root/headers/*
