FROM ubuntu:focal AS focal

RUN apt update;
RUN apt install -y wget curl tree git gcc build-essential kbuild libelf-dev;
RUN apt-get -y install linux-headers-*-generic || true
RUN apt clean all

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./batch_compile.sh

RUN apt-get -y remove linux-headers-*-generic || true