FROM ubuntu:xenial AS xenial_aws

RUN apt update;
RUN apt install -y wget curl tree git gcc build-essential kbuild libelf-dev;
RUN apt-get -y install linux-headers-*-aws || true
RUN apt clean all

ADD . /elkeid_driver
WORKDIR /elkeid_driver
RUN bash ./batch_compile.sh

RUN apt-get -y remove linux-headers-*-aws || true
