FROM arm64v8/oraclelinux:8 AS rhel8


RUN dnf install -y wget perl gcc make tree elfutils-libelf-devel yumdownloader gnutls-utils pciutils-libs; 
RUN dnf groupinstall -y  "Development Tools"; 
RUN dnf install -y centos-release-scl
RUN dnf install -y devtoolset-8

RUN rm -rf /root/headers || true
RUN mkdir /root/headers

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/aarch64/batch_compile_el7.sh