FROM arm64v8/centos:centos7.9.2009 AS rhel7


RUN yum install -y wget perl gcc make tree elfutils-libelf-devel yumdownloader gnutls-utils pciutils-libs; 
RUN yum groupinstall -y  "Development Tools"; 
RUN yum install -y centos-release-scl
RUN yum install -y devtoolset-8
RUN rm -rf /root/headers || true
RUN mkdir /root/headers

ADD . /elkeid
WORKDIR /elkeid/driver
RUN bash ./build_script/aarch64/batch_compile_el7.sh