build:
	cargo build --bin elkeid_rasp --release

build-debug:
	cargo build --bin elkeid_rasp

build-musl:
	cargo build --bin elkeid_rasp --release --target x86_64-unknown-linux-musl

clean:
	cargo clean
