build:
	cargo build --bin elkeid_rasp --release --features bin_mode

build-debug:
	cargo build --bin elkeid_rasp --features bin_mode

build-musl:
	cargo build --bin elkeid_rasp --release --target x86_64-unknown-linux-musl --features bin_mode

clean:
	cargo clean
