name: Elkeid_plugin_scanner

on:
  push:
    branches:
    - main
    paths:
    - plugins/scanner/**

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Scanner
      uses: docker/build-push-action@v2
      with:
        file: plugins/scanner/docker/Dockerfile
        load: true
        tags: elkeid/scanner:latest

    - name: Extract Scanner
      id: extract-scanner
      uses: shrink/actions-docker-extract@v1
      with:
        image: elkeid/scanner:latest
        path: /Elkeid/plugins/scanner/output/.

    - name: Upload Scanner
      uses: actions/upload-artifact@v4
      with:
        path: ${{ steps.extract-scanner.outputs.destination }}
        name: scanner