name: Elkeid_plugin_scanner_x86_64

on:
  push:
    branches:
    - main
    - 1.9/scanner
    - 2.0/scanner

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Scanner
      uses: docker/build-push-action@v3
      with:
        file: plugins/scanner/docker/Dockerfile.x86_64
        load: true
        tags: elkeid/scanner_x86_64:latest

    - name: Extract Scanner
      id: extract-scanner
      uses: shrink/actions-docker-extract@v1
      with:
        image: elkeid/scanner_x86_64:latest
        path: /Elkeid/plugins/scanner/output/.

    - name: Upload Scanner
      uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.extract-scanner.outputs.destination }}
        name: scanner_x86_64